spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mynotes
    username: mynotes
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
